name: pages-publish
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, tag or SHA to checkout
        required: false
        type: string
        default: null
  release:
    types: [published]

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler/test exec tsc #typecheck tests
      - run: pnpm -C compiler coverage
      - run: pnpm -C compiler build
      - run: pnpm -C website build
      - run: pnpm -C website docs:copy
      - name: Deploy
        run: |
          git add -f compiler/dist docs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "[actions] build website"
          git push origin ci -f
